const vocabDataA1 = [
    { "id": 1001, "en": "about", "phonetic": "อะเบาท์", "th": "เกี่ยวกับ" },
    { "id": 1002, "en": "above", "phonetic": "อะโบฟ", "th": "เหนือ, ข้างบน" },
    { "id": 1003, "en": "across", "phonetic": "อะครอส", "th": "ข้าม" },
    { "id": 1004, "en": "action", "phonetic": "แอคชั่น", "th": "การกระทำ" },
    { "id": 1005, "en": "activity", "phonetic": "แอคทิวิตี้", "th": "กิจกรรม" },
    { "id": 1006, "en": "actor", "phonetic": "แอคเตอร์", "th": "นักแสดงชาย" },
    { "id": 1007, "en": "actress", "phonetic": "แอคเทรส", "th": "นักแสดงหญิง" },
    { "id": 1008, "en": "add", "phonetic": "แอด", "th": "เพิ่ม, บวก" },
    { "id": 1009, "en": "address", "phonetic": "แอดเดรส", "th": "ที่อยู่" },
    { "id": 1010, "en": "adult", "phonetic": "อะดัลท์", "th": "ผู้ใหญ่" },
    { "id": 1011, "en": "advice", "phonetic": "แอดไวซ์", "th": "คำแนะนำ" },
    { "id": 1012, "en": "afraid", "phonetic": "อะเฟรด", "th": "กลัว" },
    { "id": 1013, "en": "after", "phonetic": "อาฟเตอร์", "th": "หลังจาก" },
    { "id": 1014, "en": "afternoon", "phonetic": "อาฟเตอร์นูน", "th": "ตอนบ่าย" },
    { "id": 1015, "en": "again", "phonetic": "อะเกน", "th": "อีกครั้ง" },
    { "id": 1016, "en": "age", "phonetic": "เอจ", "th": "อายุ" },
    { "id": 1017, "en": "ago", "phonetic": "อะโก", "th": "ที่แล้ว (เวลา)" },
    { "id": 1018, "en": "agree", "phonetic": "อะกรี", "th": "เห็นด้วย" },
    { "id": 1019, "en": "air", "phonetic": "แอร์", "th": "อากาศ" },
    { "id": 1020, "en": "airport", "phonetic": "แอร์พอร์ต", "th": "สนามบิน" },
    { "id": 1021, "en": "all", "phonetic": "ออล", "th": "ทั้งหมด" },
    { "id": 1022, "en": "also", "phonetic": "ออลโซ", "th": "ด้วย, เช่นกัน" },
    { "id": 1023, "en": "always", "phonetic": "ออลเวย์ส", "th": "เสมอ" },
    { "id": 1024, "en": "amazing", "phonetic": "อะเมซิ่ง", "th": "น่าทึ่ง" },
    { "id": 1025, "en": "and", "phonetic": "แอนด์", "th": "และ" },
    { "id": 1026, "en": "angry", "phonetic": "แองกรี้", "th": "โกรธ" },
    { "id": 1027, "en": "animal", "phonetic": "แอนิมอล", "th": "สัตว์" },
    { "id": 1028, "en": "another", "phonetic": "อะนาเธอร์", "th": "อีกอันหนึ่ง" },
    { "id": 1029, "en": "answer", "phonetic": "แอนเซอร์", "th": "คำตอบ, ตอบ" },
    { "id": 1030, "en": "any", "phonetic": "เอนี่", "th": "ใดๆ" },
    { "id": 1031, "en": "anyone", "phonetic": "เอนี่วัน", "th": "ใครก็ได้" },
    { "id": 1032, "en": "anything", "phonetic": "เอนี่ติง", "th": "อะไรก็ได้" },
    { "id": 1033, "en": "apartment", "phonetic": "อะพาร์ตเมนต์", "th": "ห้องชุด" },
    { "id": 1034, "en": "apple", "phonetic": "แอปเปิ้ล", "th": "แอปเปิ้ล" },
    { "id": 1035, "en": "april", "phonetic": "เอพริล", "th": "เมษายน" },
    { "id": 1036, "en": "area", "phonetic": "แอเรีย", "th": "พื้นที่" },
    { "id": 1037, "en": "arm", "phonetic": "อาร์ม", "th": "แขน" },
    { "id": 1038, "en": "around", "phonetic": "อะราวด์", "th": "รอบๆ" },
    { "id": 1039, "en": "arrive", "phonetic": "อะไรฟ์", "th": "มาถึง" },
    { "id": 1040, "en": "art", "phonetic": "อาร์ต", "th": "ศิลปะ" },
    { "id": 1041, "en": "article", "phonetic": "อาร์ติเคิล", "th": "บทความ" },
    { "id": 1042, "en": "artist", "phonetic": "อาร์ทิสต์", "th": "ศิลปิน" },
    { "id": 1043, "en": "ask", "phonetic": "อาสก์", "th": "ถาม" },
    { "id": 1044, "en": "at", "phonetic": "แอท", "th": "ที่" },
    { "id": 1045, "en": "august", "phonetic": "ออกัสต์", "th": "สิงหาคม" },
    { "id": 1046, "en": "aunt", "phonetic": "อานท์", "th": "ป้า, น้า, อา" },
    { "id": 1047, "en": "autumn", "phonetic": "ออทัมน์", "th": "ฤดูใบไม้ร่วง" },
    { "id": 1048, "en": "away", "phonetic": "อะเวย์", "th": "ออกไป" },
    { "id": 1049, "en": "baby", "phonetic": "เบบี้", "th": "ทารก" },
    { "id": 1050, "en": "back", "phonetic": "แบ็ค", "th": "ด้านหลัง, กลับ" },
    { "id": 1051, "en": "bad", "phonetic": "แบด", "th": "แย่, เลว" },
    { "id": 1052, "en": "bag", "phonetic": "แบ็ก", "th": "กระเป๋า" },
    { "id": 1053, "en": "ball", "phonetic": "บอล", "th": "ลูกบอล" },
    { "id": 1054, "en": "banana", "phonetic": "บานาน่า", "th": "กล้วย" },
    { "id": 1055, "en": "band", "phonetic": "แบนด์", "th": "วงดนตรี" },
    { "id": 1056, "en": "bank", "phonetic": "แบงก์", "th": "ธนาคาร" },
    { "id": 1057, "en": "bath", "phonetic": "บาธ", "th": "อ่างอาบน้ำ" },
    { "id": 1058, "en": "bathroom", "phonetic": "บาธรูม", "th": "ห้องน้ำ" },
    { "id": 1059, "en": "be", "phonetic": "บี", "th": "เป็น, อยู่, คือ" },
    { "id": 1060, "en": "beach", "phonetic": "บีช", "th": "ชายหาด" },
    { "id": 1061, "en": "beautiful", "phonetic": "บิวตี้ฟูล", "th": "สวยงาม" },
    { "id": 1062, "en": "because", "phonetic": "บีคอส", "th": "เพราะว่า" },
    { "id": 1063, "en": "become", "phonetic": "บีคัม", "th": "กลายเป็น" },
    { "id": 1064, "en": "bed", "phonetic": "เบด", "th": "เตียง" },
    { "id": 1065, "en": "bedroom", "phonetic": "เบดรูม", "th": "ห้องนอน" },
    { "id": 1066, "en": "beer", "phonetic": "เบียร์", "th": "เบียร์" },
    { "id": 1067, "en": "before", "phonetic": "บีฟอร์", "th": "ก่อน" },
    { "id": 1068, "en": "begin", "phonetic": "บีกิน", "th": "เริ่มต้น" },
    { "id": 1069, "en": "beginning", "phonetic": "บีกินนิ่ง", "th": "การเริ่มต้น" },
    { "id": 1070, "en": "behind", "phonetic": "บีไฮด์", "th": "ข้างหลัง" },
    { "id": 1071, "en": "believe", "phonetic": "บีลีฟ", "th": "เชื่อ" },
    { "id": 1072, "en": "below", "phonetic": "บีโลว์", "th": "ข้างล่าง" },
    { "id": 1073, "en": "best", "phonetic": "เบสท์", "th": "ดีที่สุด" },
    { "id": 1074, "en": "better", "phonetic": "เบทเทอร์", "th": "ดีกว่า" },
    { "id": 1075, "en": "between", "phonetic": "บีทวีน", "th": "ระหว่าง" },
    { "id": 1076, "en": "bicycle", "phonetic": "ไบซิเคิล", "th": "รถจักรยาน" },
    { "id": 1077, "en": "big", "phonetic": "บิ๊ก", "th": "ใหญ่" },
    { "id": 1078, "en": "bike", "phonetic": "ไบค์", "th": "จักรยาน" },
    { "id": 1079, "en": "bill", "phonetic": "บิล", "th": "ใบแจ้งหนี้" },
    { "id": 1080, "en": "bird", "phonetic": "เบิร์ด", "th": "นก" },
    { "id": 1081, "en": "birthday", "phonetic": "เบิร์ธเดย์", "th": "วันเกิด" },
    { "id": 1082, "en": "black", "phonetic": "แบล็ก", "th": "สีดำ" },
    { "id": 1083, "en": "blog", "phonetic": "บล็อก", "th": "บล็อก, เว็บไซต์ส่วนตัว" },
    { "id": 1084, "en": "blonde", "phonetic": "บลอนด์", "th": "สีผมบลอนด์" },
    { "id": 1085, "en": "blue", "phonetic": "บลู", "th": "สีน้ำเงิน" },
    { "id": 1086, "en": "boat", "phonetic": "โบ๊ต", "th": "เรือ" },
    { "id": 1087, "en": "body", "phonetic": "บอดี้", "th": "ร่างกาย" },
    { "id": 1088, "en": "book", "phonetic": "บุ๊ก", "th": "หนังสือ" },
    { "id": 1089, "en": "boot", "phonetic": "บู๊ต", "th": "รองเท้าบู๊ต" },
    { "id": 1090, "en": "bored", "phonetic": "บอร์ด", "th": "รู้สึกเบื่อ" },
    { "id": 1091, "en": "boring", "phonetic": "บอริ่ง", "th": "น่าเบื่อ" },
    { "id": 1092, "en": "born", "phonetic": "บอร์น", "th": "เกิด" },
    { "id": 1093, "en": "both", "phonetic": "โบธ", "th": "ทั้งคู่" },
    { "id": 1094, "en": "bottle", "phonetic": "บอทเทิล", "th": "ขวด" },
    { "id": 1095, "en": "box", "phonetic": "บ็อกซ์", "th": "กล่อง" },
    { "id": 1096, "en": "boy", "phonetic": "บอย", "th": "เด็กผู้ชาย" },
    { "id": 1097, "en": "boyfriend", "phonetic": "บอยเฟรนด์", "th": "แฟนหนุ่ม" },
    { "id": 1098, "en": "bread", "phonetic": "เบรด", "th": "ขนมปัง" },
    { "id": 1099, "en": "break", "phonetic": "เบรก", "th": "พัก, แตกหัก" },
    { "id": 1100, "en": "breakfast", "phonetic": "เบรกฟาสต์", "th": "อาหารเช้า" },
    { "id": 1101, "en": "bring", "phonetic": "บริง", "th": "นำมา" },
    { "id": 1102, "en": "brother", "phonetic": "บราเธอร์", "th": "พี่ชาย, น้องชาย" },
    { "id": 1103, "en": "brown", "phonetic": "บราวน์", "th": "สีน้ำตาล" },
    { "id": 1104, "en": "build", "phonetic": "บิลด์", "th": "สร้าง" },
    { "id": 1105, "en": "building", "phonetic": "บิลดิ้ง", "th": "อาคาร" },
    { "id": 1106, "en": "bus", "phonetic": "บัส", "th": "รถบัส" },
    { "id": 1107, "en": "business", "phonetic": "บิสเนส", "th": "ธุรกิจ" },
    { "id": 1108, "en": "busy", "phonetic": "บิซี่", "th": "ยุ่ง" },
    { "id": 1109, "en": "but", "phonetic": "บัท", "th": "แต่" },
    { "id": 1110, "en": "butter", "phonetic": "บัทเทอร์", "th": "เนย" },
    { "id": 1111, "en": "buy", "phonetic": "บาย", "th": "ซื้อ" },
    { "id": 1112, "en": "by", "phonetic": "บาย", "th": "โดย" },
    { "id": 1113, "en": "cafe", "phonetic": "คาเฟ่", "th": "ร้านกาแฟ" },
    { "id": 1114, "en": "cake", "phonetic": "เค้ก", "th": "เค้ก" },
    { "id": 1115, "en": "call", "phonetic": "คอล", "th": "เรียก, โทร" },
    { "id": 1116, "en": "camera", "phonetic": "คาเมร่า", "th": "กล้องถ่ายรูป" },
    { "id": 1117, "en": "can", "phonetic": "แคน", "th": "สามารถ" },
    { "id": 1118, "en": "cannot", "phonetic": "แคนนอท", "th": "ไม่สามารถ" },
    { "id": 1119, "en": "capital", "phonetic": "แคปปิตอล", "th": "เมืองหลวง" },
    { "id": 1120, "en": "car", "phonetic": "คาร์", "th": "รถยนต์" },
    { "id": 1121, "en": "card", "phonetic": "การ์ด", "th": "บัตร, ไพ่" },
    { "id": 1122, "en": "career", "phonetic": "คาเรียร์", "th": "อาชีพ" },
    { "id": 1123, "en": "carrot", "phonetic": "แครอท", "th": "แครอท" },
    { "id": 1124, "en": "carry", "phonetic": "แครี่", "th": "ถือ, แบก" },
    { "id": 1125, "en": "cat", "phonetic": "แคท", "th": "แมว" },
    { "id": 1126, "en": "catch", "phonetic": "แคทช์", "th": "จับ" },
    { "id": 1127, "en": "center", "phonetic": "เซ็นเตอร์", "th": "ศูนย์กลาง" },
    { "id": 1128, "en": "century", "phonetic": "เซ็นจูรี่", "th": "ศตวรรษ" },
    { "id": 1129, "en": "chair", "phonetic": "แชร์", "th": "เก้าอี้" },
    { "id": 1130, "en": "change", "phonetic": "เชนจ์", "th": "เปลี่ยน" },
    { "id": 1131, "en": "chart", "phonetic": "ชาร์ต", "th": "แผนภูมิ" },
    { "id": 1132, "en": "cheap", "phonetic": "ชีป", "th": "ราคาถูก" },
    { "id": 1133, "en": "check", "phonetic": "เช็ค", "th": "ตรวจสอบ" },
    { "id": 1134, "en": "cheese", "phonetic": "ชีส", "th": "เนยแข็ง" },
    { "id": 1135, "en": "chicken", "phonetic": "ชิคเก้น", "th": "ไก่" },
    { "id": 1136, "en": "child", "phonetic": "ไชลด์", "th": "เด็ก" },
    { "id": 1137, "en": "chocolate", "phonetic": "ช็อกโกแลต", "th": "ช็อกโกแลต" },
    { "id": 1138, "en": "choose", "phonetic": "ชูส", "th": "เลือก" },
    { "id": 1139, "en": "city", "phonetic": "ซิตี้", "th": "เมือง" },
    { "id": 1140, "en": "class", "phonetic": "คลาส", "th": "ชั้นเรียน" },
    { "id": 1141, "en": "clean", "phonetic": "คลีน", "th": "สะอาด" },
    { "id": 1142, "en": "clear", "phonetic": "เคลียร์", "th": "ชัดเจน" },
    { "id": 1143, "en": "clever", "phonetic": "เคลเวอร์", "th": "ฉลาด" },
    { "id": 1144, "en": "clock", "phonetic": "คล็อก", "th": "นาฬิกา" },
    { "id": 1145, "en": "close", "phonetic": "โคลส", "th": "ปิด, ใกล้" },
    { "id": 1146, "en": "clothes", "phonetic": "โคลธส", "th": "เสื้อผ้า" },
    { "id": 1147, "en": "club", "phonetic": "คลับ", "th": "สโมสร" },
    { "id": 1148, "en": "coat", "phonetic": "โค้ท", "th": "เสื้อคลุม" },
    { "id": 1149, "en": "coffee", "phonetic": "คอฟฟี่", "th": "กาแฟ" },
    { "id": 1150, "en": "cold", "phonetic": "โคลด์", "th": "หนาว, เย็น" },
    { "id": 1151, "en": "college", "phonetic": "คอลเลจ", "th": "วิทยาลัย" },
    { "id": 1152, "en": "color", "phonetic": "คัลเลอร์", "th": "สี" },
    { "id": 1153, "en": "come", "phonetic": "คัม", "th": "มา" },
    { "id": 1154, "en": "common", "phonetic": "คอมมอน", "th": "ธรรมดา, ทั่วไป" },
    { "id": 1155, "en": "company", "phonetic": "คัมพานี", "th": "บริษัท" },
    { "id": 1156, "en": "compare", "phonetic": "คอมแพร์", "th": "เปรียบเทียบ" },
    { "id": 1157, "en": "complete", "phonetic": "คอมพลีต", "th": "สมบูรณ์, ทำให้เสร็จ" },
    { "id": 1158, "en": "computer", "phonetic": "คอมพิวเตอร์", "th": "คอมพิวเตอร์" },
    { "id": 1159, "en": "concert", "phonetic": "คอนเสิร์ต", "th": "คอนเสิร์ต" },
    { "id": 1160, "en": "conversation", "phonetic": "คอนเวอร์เซชั่น", "th": "บทสนทนา" },
    { "id": 1161, "en": "cook", "phonetic": "คุก", "th": "ทำอาหาร" },
    { "id": 1162, "en": "cooking", "phonetic": "คุกกิ้ง", "th": "การทำอาหาร" },
    { "id": 1163, "en": "cool", "phonetic": "คูล", "th": "เย็น, เจ๋ง" },
    { "id": 1164, "en": "correct", "phonetic": "คอร์เรคต์", "th": "ถูกต้อง" },
    { "id": 1165, "en": "cost", "phonetic": "คอสต์", "th": "ราคา" },
    { "id": 1166, "en": "could", "phonetic": "คูลด์", "th": "สามารถ (อดีต)" },
    { "id": 1167, "en": "country", "phonetic": "คันทรี", "th": "ประเทศ" },
    { "id": 1168, "en": "course", "phonetic": "คอร์ส", "th": "หลักสูตร" },
    { "id": 1169, "en": "cousin", "phonetic": "คัซซิน", "th": "ลูกพี่ลูกน้อง" },
    { "id": 1170, "en": "cow", "phonetic": "คาว", "th": "วัว" },
    { "id": 1171, "en": "create", "phonetic": "ครีเอท", "th": "สร้าง" },
    { "id": 1172, "en": "culture", "phonetic": "คัลเชอร์", "th": "วัฒนธรรม" },
    { "id": 1173, "en": "cup", "phonetic": "คัพ", "th": "ถ้วย" },
    { "id": 1174, "en": "customer", "phonetic": "คัสโตเมอร์", "th": "ลูกค้า" },
    { "id": 1175, "en": "cut", "phonetic": "คัท", "th": "ตัด" },
    { "id": 1176, "en": "dad", "phonetic": "แดด", "th": "พ่อ" },
    { "id": 1177, "en": "dance", "phonetic": "แดนซ์", "th": "เต้น" },
    { "id": 1178, "en": "dancer", "phonetic": "แดนซ์เซอร์", "th": "นักเต้น" },
    { "id": 1179, "en": "danger", "phonetic": "เดนเจอร์", "th": "อันตราย" },
    { "id": 1180, "en": "dangerous", "phonetic": "เดนเจอร์รัส", "th": "ซึ่งมีอันตราย" },
    { "id": 1181, "en": "dark", "phonetic": "ดาร์ค", "th": "มืด" },
    { "id": 1182, "en": "date", "phonetic": "เดท", "th": "วันที่, การนัดพบ" },
    { "id": 1183, "en": "daughter", "phonetic": "ดอเทอร์", "th": "ลูกสาว" },
    { "id": 1184, "en": "day", "phonetic": "เดย์", "th": "วัน" },
    { "id": 1185, "en": "dead", "phonetic": "เดด", "th": "ตายแล้ว" },
    { "id": 1186, "en": "dear", "phonetic": "เดียร์", "th": "ที่รัก" },
    { "id": 1187, "en": "death", "phonetic": "เดธ", "th": "ความตาย" },
    { "id": 1188, "en": "decide", "phonetic": "ดีไซด์", "th": "ตัดสินใจ" },
    { "id": 1189, "en": "delicious", "phonetic": "ดีลิเชียส", "th": "อร่อย" },
    { "id": 1190, "en": "describe", "phonetic": "ดิสไครบ์", "th": "บรรยาย" },
    { "id": 1191, "en": "design", "phonetic": "ดีไซน์", "th": "ออกแบบ" },
    { "id": 1192, "en": "desk", "phonetic": "เดสก์", "th": "โต๊ะเรียน/ทำงาน" },
    { "id": 1193, "en": "detail", "phonetic": "ดีเทล", "th": "รายละเอียด" },
    { "id": 1194, "en": "dialogue", "phonetic": "ไดอะล็อก", "th": "บทสนทนา" },
    { "id": 1195, "en": "dictionary", "phonetic": "ดิกชันนารี", "th": "พจนานุกรม" },
    { "id": 1196, "en": "die", "phonetic": "ดาย", "th": "ตาย" },
    { "id": 1197, "en": "diet", "phonetic": "ไดเอท", "th": "อาหาร, ควบคุมอาหาร" },
    { "id": 1198, "en": "difference", "phonetic": "ดิฟเฟอเรนซ์", "th": "ความแตกต่าง" },
    { "id": 1199, "en": "different", "phonetic": "ดิฟเฟอเรนต์", "th": "ที่แตกต่าง" },
    { "id": 1200, "en": "difficult", "phonetic": "ดิฟฟิคัลท์", "th": "ยาก" },
    { "id": 1201, "en": "dinner", "phonetic": "ดินเนอร์", "th": "อาหารเย็น" },
    { "id": 1202, "en": "dirty", "phonetic": "เดอร์ตี้", "th": "สกปรก" },
    { "id": 1203, "en": "discuss", "phonetic": "ดิสคัส", "th": "สนทนา, ถกเถียง" },
    { "id": 1204, "en": "dish", "phonetic": "ดิช", "th": "จานอาหาร" },
    { "id": 1205, "en": "do", "phonetic": "ดู", "th": "ทำ" },
    { "id": 1206, "en": "doctor", "phonetic": "ด็อกเตอร์", "th": "หมอ" },
    { "id": 1207, "en": "dog", "phonetic": "ด็อก", "th": "หมา" },
    { "id": 1208, "en": "door", "phonetic": "ดอร์", "th": "ประตู" },
    { "id": 1209, "en": "down", "phonetic": "ดาวน์", "th": "ลง" },
    { "id": 1210, "en": "draw", "phonetic": "ดรอว์", "th": "วาด" },
    { "id": 1211, "en": "dress", "phonetic": "เดรส", "th": "ชุดกระโปรง" },
    { "id": 1212, "en": "drink", "phonetic": "ดริงก์", "th": "ดื่ม" },
    { "id": 1213, "en": "drive", "phonetic": "ไดรฟ์", "th": "ขับรถ" },
    { "id": 1214, "en": "driver", "phonetic": "ไดรเวอร์", "th": "คนขับ" },
    { "id": 1215, "en": "during", "phonetic": "ดิวริ่ง", "th": "ระหว่าง" },
    { "id": 1216, "en": "each", "phonetic": "อีช", "th": "แต่ละ" },
    { "id": 1217, "en": "early", "phonetic": "เออร์ลี่", "th": "ก่อนเวลา, แต่เช้า" },
    { "id": 1218, "en": "east", "phonetic": "อีสต์", "th": "ทิศตะวันออก" },
    { "id": 1219, "en": "easy", "phonetic": "อีซี่", "th": "ง่าย" },
    { "id": 1220, "en": "eat", "phonetic": "อีท", "th": "กิน" },
    { "id": 1221, "en": "egg", "phonetic": "เอ้ก", "th": "ไข่" },
    { "id": 1222, "en": "eight", "phonetic": "เอท", "th": "แปด" },
    { "id": 1223, "en": "eighteen", "phonetic": "เอททีน", "th": "สิบแปด" },
    { "id": 1224, "en": "eighty", "phonetic": "เอทตี้", "th": "แปดสิบ" },
    { "id": 1225, "en": "elephant", "phonetic": "เอเลเฟ่นท์", "th": "ช้าง" },
    { "id": 1226, "en": "eleven", "phonetic": "อีเลฟเว่น", "th": "สิบเอ็ด" },
    { "id": 1227, "en": "else", "phonetic": "เอลส์", "th": "อื่นๆ, อีก" },
    { "id": 1228, "en": "email", "phonetic": "อีเมล", "th": "อีเมล" },
    { "id": 1229, "en": "end", "phonetic": "เอนด์", "th": "จบ" },
    { "id": 1230, "en": "enjoy", "phonetic": "เอนจอย", "th": "สนุกกับ" },
    { "id": 1231, "en": "enough", "phonetic": "อินาฟ", "th": "เพียงพอ" },
    { "id": 1232, "en": "evening", "phonetic": "อีฟนิ่ง", "th": "ตอนเย็น" },
    { "id": 1233, "en": "event", "phonetic": "อีเวนต์", "th": "เหตุการณ์" },
    { "id": 1234, "en": "ever", "phonetic": "เอเวอร์", "th": "เคย" },
    { "id": 1235, "en": "every", "phonetic": "เอฟรี่", "th": "ทุกๆ" },
    { "id": 1236, "en": "everyone", "phonetic": "เอฟรี่วัน", "th": "ทุกคน" },
    { "id": 1237, "en": "everything", "phonetic": "เอฟรี่ติง", "th": "ทุกสิ่งทุกอย่าง" },
    { "id": 1238, "en": "exam", "phonetic": "เอ็กแซม", "th": "การสอบ" },
    { "id": 1239, "en": "example", "phonetic": "เอ็กแซมเปิล", "th": "ตัวอย่าง" },
    { "id": 1240, "en": "excited", "phonetic": "เอ็กไซเต็ด", "th": "รู้สึกตื่นเต้น" },
    { "id": 1241, "en": "exciting", "phonetic": "เอ็กไซติ้ง", "th": "น่าตื่นเต้น" },
    { "id": 1242, "en": "exercise", "phonetic": "เอ็กเซอร์ไซส์", "th": "ออกกำลังกาย, แบบฝึกหัด" },
    { "id": 1243, "en": "expensive", "phonetic": "เอ็กซ์เพนซีฟ", "th": "แพง" },
    { "id": 1244, "en": "explain", "phonetic": "เอ็กซ์เพลน", "th": "อธิบาย" },
    { "id": 1245, "en": "eye", "phonetic": "อาย", "th": "ตา" },
    { "id": 1246, "en": "face", "phonetic": "เฟส", "th": "ใบหน้า" },
    { "id": 1247, "en": "fact", "phonetic": "แฟคต์", "th": "ข้อเท็จจริง" },
    { "id": 1248, "en": "fall", "phonetic": "ฟอล", "th": "ตก, ฤดูใบไม้ร่วง" },
    { "id": 1249, "en": "family", "phonetic": "แฟมิลี่", "th": "ครอบครัว" },
    { "id": 1250, "en": "famous", "phonetic": "เฟมัส", "th": "มีชื่อเสียง" },
    { "id": 1251, "en": "far", "phonetic": "ฟาร์", "th": "ไกล" },
    { "id": 1252, "en": "farm", "phonetic": "ฟาร์ม", "th": "ฟาร์ม" },
    { "id": 1253, "en": "fast", "phonetic": "ฟาสต์", "th": "เร็ว" },
    { "id": 1254, "en": "father", "phonetic": "ฟาเธอร์", "th": "พ่อ" },
    { "id": 1255, "en": "favorite", "phonetic": "เฟเวอริท", "th": "ที่ชื่นชอบ" },
    { "id": 1256, "en": "feel", "phonetic": "ฟีล", "th": "รู้สึก" },
    { "id": 1257, "en": "festival", "phonetic": "เฟสติวัล", "th": "เทศกาล" },
    { "id": 1258, "en": "few", "phonetic": "ฟิว", "th": "เล็กน้อย" },
    { "id": 1259, "en": "fifteen", "phonetic": "ฟิฟทีน", "th": "สิบห้า" },
    { "id": 1260, "en": "fifty", "phonetic": "ฟิฟตี้", "th": "ห้าสิบ" },
    { "id": 1261, "en": "fill", "phonetic": "ฟิล", "th": "เติม" },
    { "id": 1262, "en": "film", "phonetic": "ฟิล์ม", "th": "ภาพยนตร์" },
    { "id": 1263, "en": "find", "phonetic": "ไฟนด์", "th": "พบ, หา" },
    { "id": 1264, "en": "fine", "phonetic": "ไฟน์", "th": "สบายดี, ค่าปรับ" },
    { "id": 1265, "en": "finish", "phonetic": "ฟินิช", "th": "เสร็จ" },
    { "id": 1266, "en": "fire", "phonetic": "ไฟร์", "th": "ไฟ" },
    { "id": 1267, "en": "first", "phonetic": "เฟิร์สต์", "th": "อันดับแรก" },
    { "id": 1268, "en": "fish", "phonetic": "ฟิช", "th": "ปลา" },
    { "id": 1269, "en": "five", "phonetic": "ไฟฟ์", "th": "ห้า" },
    { "id": 1270, "en": "flat", "phonetic": "แฟลต", "th": "แบน, อพาร์ตเมนต์" },
    { "id": 1271, "en": "flight", "phonetic": "ไฟลท์", "th": "เที่ยวบิน" },
    { "id": 1272, "en": "floor", "phonetic": "ฟลอร์", "th": "พื้น" },
    { "id": 1273, "en": "flower", "phonetic": "ฟลาวเวอร์", "th": "ดอกไม้" },
    { "id": 1274, "en": "fly", "phonetic": "ฟลาย", "th": "บิน" },
    { "id": 1275, "en": "food", "phonetic": "ฟู้ด", "th": "อาหาร" },
    { "id": 1276, "en": "foot", "phonetic": "ฟุต", "th": "เท้า" },
    { "id": 1277, "en": "football", "phonetic": "ฟุตบอล", "th": "ฟุตบอล" },
    { "id": 1278, "en": "for", "phonetic": "ฟอร์", "th": "สำหรับ" },
    { "id": 1279, "en": "forget", "phonetic": "ฟอร์เก็ต", "th": "ลืม" },
    { "id": 1280, "en": "form", "phonetic": "ฟอร์ม", "th": "รูปแบบ, แบบฟอร์ม" },
    { "id": 1281, "en": "four", "phonetic": "โฟร์", "th": "สี่" },
    { "id": 1282, "en": "fourteen", "phonetic": "โฟร์ทีน", "th": "สิบสี่" },
    { "id": 1283, "en": "forty", "phonetic": "ฟอร์ตี้", "th": "สี่สิบ" },
    { "id": 1284, "en": "free", "phonetic": "ฟรี", "th": "ฟรี, ว่าง" },
    { "id": 1285, "en": "friday", "phonetic": "ไฟรเดย์", "th": "วันศุกร์" },
    { "id": 1286, "en": "friend", "phonetic": "เฟรนด์", "th": "เพื่อน" },
    { "id": 1287, "en": "friendly", "phonetic": "เฟรนด์ลี่", "th": "เป็นมิตร" },
    { "id": 1288, "en": "from", "phonetic": "ฟรอม", "th": "จาก" },
    { "id": 1289, "en": "front", "phonetic": "ฟรอนต์", "th": "ด้านหน้า" },
    { "id": 1290, "en": "fruit", "phonetic": "ฟรุต", "th": "ผลไม้" },
    { "id": 1291, "en": "full", "phonetic": "ฟูล", "th": "เต็ม" },
    { "id": 1292, "en": "fun", "phonetic": "ฟัน", "th": "สนุก" },
    { "id": 1293, "en": "funny", "phonetic": "ฟันนี่", "th": "ตลก" },
    { "id": 1294, "en": "future", "phonetic": "ฟิวเจอร์", "th": "อนาคต" },
    { "id": 1295, "en": "game", "phonetic": "เกม", "th": "เกม" },
    { "id": 1296, "en": "garden", "phonetic": "การ์เด้น", "th": "สวน" },
    { "id": 1297, "en": "get", "phonetic": "เก็ท", "th": "ได้รับ" },
    { "id": 1298, "en": "girl", "phonetic": "เกิร์ล", "th": "เด็กผู้หญิง" },
    { "id": 1299, "en": "girlfriend", "phonetic": "เกิร์ลเฟรนด์", "th": "แฟนสาว" },
    { "id": 1300, "en": "give", "phonetic": "กีฟ", "th": "ให้" }
];
