import json

new_words = {
    'toeic_listening': [
        ('Aisle', 'ไอล', 'ทางเดิน', 'Noun', 'Please keep your bags out of the aisle.', 'กรุณาอย่าวางกระเป๋าขวางทางเดิน'),
        ('Baggage', 'แบก-เกจ', 'สัมภาระ', 'Noun', 'You can claim your baggage at carousel 3.', 'คุณสามารถรับสัมภาระได้ที่สายพาน 3'),
        ('Counter', 'เคาน์-เตอร์', 'เคาน์เตอร์', 'Noun', 'Please proceed to the check-in counter.', 'กรุณาไปที่เคาน์เตอร์เช็คอิน'),
        ('Destination', 'เดส-ทิ-เน-ชัน', 'จุดหมายปลายทาง', 'Noun', 'What is your final destination?', 'จุดหมายปลายทางของคุณคือที่ไหน?'),
        ('Familiar', 'ฟา-มิล-เลียร์', 'คุ้นเคย', 'Adjective', 'Are you familiar with this software?', 'คุณคุ้นเคยกับซอฟต์แวร์นี้หรือไม่?'),
        ('Guarantee', 'แก-รัน-ตี', 'รับประกัน', 'Verb', 'We guarantee the best price.', 'เรารับประกันราคาดีที่สุด'),
        ('Information', 'อิน-ฟอร์-เม-ชัน', 'ข้อมูล', 'Noun', 'For more information, visit our website.', 'สำหรับข้อมูลเพิ่มเติม โปรดเยี่ยมชมเว็บไซต์ของเรา'),
        ('Journal', 'เจอร์-นัล', 'วารสาร', 'Noun', 'He published his findings in a journal.', 'เขาตีพิมพ์ผลการค้นพบในวารสาร'),
        ('Machine', 'มะ-ชีน', 'เครื่องจักร', 'Noun', 'The coffee machine is broken.', 'เครื่องชงกาแฟพัง'),
        ('Occasion', 'ออ-เค-ชัน', 'โอกาส', 'Noun', 'I only wear this suit on special occasions.', 'ฉันใส่ชุดสูทนี้เฉพาะในโอกาสพิเศษเท่านั้น'),
        ('Package', 'แพค-เกจ', 'บรรจุภัณฑ์/พัสดุ', 'Noun', 'Your package has arrived.', 'พัสดุของคุณมาถึงแล้ว'),
        ('Quality', 'ควอล-ลิ-ตี', 'คุณภาพ', 'Noun', 'We focus on product quality.', 'เรามุ่งเน้นที่คุณสมบัติของผลิตภัณฑ์'),
        ('Receipt', 'รี-ซีท', 'ใบเสร็จ', 'Noun', 'Please keep your receipt as proof of purchase.', 'โปรดเก็บใบเสร็จไว้เป็นหลักฐานการซื้อ'),
        ('Signature', 'ซิก-เน-เจอร์', 'ลายเซ็น', 'Noun', 'We need your signature on this document.', 'เราต้องการลายเซ็นของคุณในเอกสารนี้'),
        ('Terminal', 'เทอร์-มิ-นัล', 'อาคารผู้โดยสาร', 'Noun', 'The flight departs from Terminal 2.', 'เที่ยวบินออกเดินทางจากอาคารผู้โดยสาร 2'),
        ('Valuable', 'แวล-ลู-เอ-เบิล', 'มีค่า', 'Adjective', 'Keep your valuable items with you.', 'เก็บของมีค่าไว้กับตัว'),
        ('Warehouse', 'แวร์-เฮาส์', 'โกดัง', 'Noun', 'The goods are stored in the warehouse.', 'สินค้าถูกเก็บไว้ในโกดัง'),
        ('Yield', 'ยิลด์', 'ผลผลิต/ให้ผล', 'Noun/Verb', 'The new strategy yielded positive results.', 'กลยุทธ์ใหม่ให้ผลลัพธ์ที่เป็นบวก'),
        ('Zone', 'โซน', 'พื้นที่', 'Noun', 'This is a no-parking zone.', 'นี่คือพื้นที่ห้ามจอด'),
        ('Accompany', 'แอค-คอม-พา-นี', 'มาด้วย/ติดตาม', 'Verb', 'Children must be accompanied by an adult.', 'เด็กต้องมีผู้ใหญ่คอยดูแล'),
        ('Board', 'บอร์ด', 'คณะกรรมการ/ขึ้น(เครื่อง)', 'Noun/Verb', 'The board of directors approved the budget.', 'คณะกรรมการอนุมัติงบประมาณ'),
        ('Cancel', 'แคน-เซิล', 'ยกเลิก', 'Verb', 'The flight was canceled due to bad weather.', 'เที่ยวบินถูกยกเลิกเนื่องจากสภาพอากาศเลวร้าย'),
        ('Damage', 'แดม-เมจ', 'ความเสียหาย', 'Noun', 'Report any damage to the manager.', 'รายงานความเสียหายใดๆ ต่อผู้จัดการ'),
        ('Economy', 'อี-คอน-โน-มี', 'เศรษฐกิจ/ชั้นประหยัด', 'Noun', 'I usually fly economy class.', 'ฉันมักจะบินชั้นประหยัด'),
        ('Forecast', 'ฟอร์-คาสท์', 'พยากรณ์', 'Verb/Noun', 'The weather forecast predicts rain.', 'พยากรณ์อากาศคาดว่าจะมีฝนตก'),
        ('Gate', 'เกท', 'ประตู(ขึ้นเครื่อง)', 'Noun', 'Proceed to gate 14 immediately.', 'ไปที่ประตู 14 ทันที'),
        ('Handle', 'แฮน-เดิล', 'จัดการ', 'Verb', 'She can handle the pressure.', 'เธอสามารถจัดการกับแรงกดดันได้'),
        ('Item', 'ไอ-เทม', 'รายการ/สิ่งของ', 'Noun', 'Please place all items in the bin.', 'โปรดวางสิ่งของทั้งหมดลงในถัง'),
        ('Join', 'จอยน์', 'เข้าร่วม', 'Verb', 'Would you like to join us for lunch?', 'คุณต้องการร่วมทานอาหารกลางวันกับเราไหม?'),
        ('Luggage', 'ลัก-เกจ', 'สัมภาระ', 'Noun', 'Do you have any checked luggage?', 'คุณมีสัมภาระโหลดใต้เครื่องหรือไม่?'),
        ('Manager', 'แมน-เน-เจอร์', 'ผู้จัดการ', 'Noun', 'The store manager is currently busy.', 'ผู้จัดการร้านกำลังยุ่งอยู่'),
        ('Notice', 'โน-ทิส', 'ประกาศ/สังเกต', 'Noun', 'Did you see the notice on the board?', 'คุณเห็นประกาศบนกระดานไหม?'),
        ('Option', 'ออป-ชัน', 'ทางเลือก', 'Noun', 'We have several payment options.', 'เรามีทางเลือกการชำระเงินหลายแบบ'),
        ('Platform', 'แพลต-ฟอร์ม', 'ชานชาลา', 'Noun', 'The train on platform 3 is ready to depart.', 'รถไฟที่ชานชาลา 3 พร้อมออกเดินทางแล้ว'),
        ('Quarter', 'ควอร์-เตอร์', 'ไตรมาส', 'Noun', 'Profits rose in the third quarter.', 'กำไรเพิ่มขึ้นในไตรมาสที่สาม'),
        ('Reservation', 'เรส-เซอร์-เว-ชัน', 'การจอง', 'Noun', 'I have a reservation under the name Smith.', 'ฉันมีการจองในชื่อสมิธ'),
        ('Security', 'ซี-คิว-ริ-ตี', 'ความปลอดภัย', 'Noun', 'Pass through security screening.', 'ผ่านการตรวจตราความปลอดภัย'),
        ('Track', 'แทรค', 'ติดตาม/ลู่', 'Verb/Noun', 'We use software to track shipments.', 'เราใช้ซอฟต์แวร์เพื่อติดตามการจัดส่ง'),
        ('Upgrade', 'อัป-เกรด', 'อัปเกรด', 'Verb/Noun', 'He received a free upgrade to first class.', 'เขาได้รับการอัปเกรดเป็นชั้นหนึ่งฟรี'),
        ('Vehicle', 'วี-ฮิ-เคิล', 'ยานพาหนะ', 'Noun', 'Park your vehicle in the designated area.', 'จอดรถของคุณในพื้นที่ที่กำหนด'),
        ('Wait', 'เวท', 'รอ', 'Verb', 'Please wait in the lobby.', 'กรุณารอที่ล็อบบี้'),
        ('Annual', 'แอน-นวล', 'ประจำปี', 'Adjective', 'The annual report will be published soon.', 'รายงานประจำปีจะได้รับการเผยแพร่ในไม่ช้า'),
        ('Balance', 'บาล-ลานซ์', 'ยอดคงเหลือ/สมดุล', 'Noun', 'Check your account balance online.', 'ตรวจสอบยอดเงินในบัญชีของคุณทางออนไลน์'),
        ('Charge', 'ชาร์จ', 'คิดราคา', 'Verb', 'There is no extra charge for delivery.', 'ไม่มีค่าธรรมเนียมเพิ่มเติมสำหรับการจัดส่ง'),
        ('Direct', 'ได-เรคท์', 'โดยตรง', 'Adjective', 'I prefer a direct flight.', 'ฉันชอบเที่ยวบินตรงมากกว่า'),
        ('Estimate', 'เอส-ทิ-เมท', 'ประมาณการ', 'Verb', 'Can you estimate the total cost?', 'คุณช่วยประมาณการค่าใช้จ่ายทั้งหมดได้ไหม?'),
        ('Frequent', 'ฟรี-เควนท์', 'บ่อย', 'Adjective', 'He is a frequent flyer.', 'เขาเป็นผู้โดยสารที่บินบ่อย'),
        ('Guest', 'เกสต์', 'แขก', 'Noun', 'We are expecting a special guest.', 'เรากำลังรอแขกคนพิเศษ'),
        ('Host', 'โฮสต์', 'เจ้าภาพ', 'Noun', 'Our company will host the event.', 'บริษัทของเราจะเป็นเจ้าภาพจัดงาน'),
        ('Issue', 'อิช-ชิว', 'ปัญหา/ออกให้', 'Noun', 'Let us resolve this issue quickly.', 'เรามาแก้ปัญหานี้กันอย่างรวดเร็ว')
    ],
    'toeic_reading': [
        ('Asset', 'แอส-เซท', 'สินทรัพย์', 'Noun', 'The company has many valuable assets.', 'บริษัทมีสินทรัพย์ที่มีค่ามากมาย'),
        ('Broker', 'โบรค-เกอร์', 'นายหน้า', 'Noun', 'The real estate broker showed us the house.', 'นายหน้าอสังหาริมทรัพย์พาเราไปดูบ้าน'),
        ('Clause', 'คลอส', 'ข้อสัญญา', 'Noun', 'Please read the penalty clause carefully.', 'โปรดอ่านข้อสัญญาการปรับอย่างละเอียด'),
        ('Deduct', 'ดี-ดัคท์', 'หักออก', 'Verb', 'Taxes will be deducted from your salary.', 'ภาษีจะถูกหักออกจากเงินเดือนของคุณ'),
        ('Exempt', 'เอกซ์-เซมพ์', 'ได้รับการยกเว้น', 'Adjective', 'Non-profit organizations are tax-exempt.', 'องค์กรไม่แสวงหาผลกำไรได้รับการยกเว้นภาษี'),
        ('Franchise', 'แฟรน-ไชส์', 'แฟรนไชส์', 'Noun', 'He owns a fast-food franchise.', 'เขาเป็นเจ้าของแฟรนไชส์ฟาสต์ฟู้ด'),
        ('Gross', 'กรอส', 'ทั้งหมด/รวม', 'Adjective', 'The gross profit margin was 40%.', 'อัตรากำไรขั้นต้นอยู่ที่ 40%'),
        ('Headquarters', 'เฮด-ควอ-เตอร์ส', 'สำนักงานใหญ่', 'Noun', 'Our headquarters is located in London.', 'สำนักงานใหญ่ของเราตั้งอยู่ในลอนดอน'),
        ('Inventory', 'อิน-เวน-ทอ-รี', 'สินค้าคงคลัง', 'Noun', 'We conduct an inventory check every month.', 'เราทำการตรวจสอบสินค้าคงคลังทุกเดือน'),
        ('Jobless', 'จ๊อบ-เลส', 'ตกงาน', 'Adjective', 'The jobless rate has decreased this year.', 'อัตราคนว่างงานลดลงในปีนี้'),
        ('Lease', 'ลีส', 'สัญญาเช่า', 'Noun/Verb', 'The office lease expires in December.', 'สัญญาเช่าสำนักงานจะหมดอายุในเดือนธันวาคม'),
        ('Margin', 'มาร์-จิน', 'ส่วนกำไร', 'Noun', 'We need to increase our profit margin.', 'เราจำเป็นต้องเพิ่มอัตรากำไรของเรา'),
        ('Net', 'เนท', 'สุทธิ', 'Adjective', 'Net income rose by 10%.', 'รายได้สุทธิเพิ่มขึ้น 10%'),
        ('Output', 'เอาท์-พุท', 'ผลผลิต', 'Noun', 'Factory output reached a new high.', 'ผลผลิตของโรงงานพุ่งแตะระดับสูงสุดใหม่'),
        ('Patent', 'แพท-เทนท์', 'สิทธิบัตร', 'Noun', 'The company filed a patent for the new technology.', 'บริษัทได้ยื่นจดสิทธิบัตรสำหรับเทคโนโลยีใหม่'),
        ('Quota', 'โคว-ตา', 'โควตา', 'Noun', 'The sales team met their monthly quota.', 'ทีมขายทำยอดได้ตามโควตารายเดือน'),
        ('Retail', 'รี-เทล', 'ขายปลีก', 'Noun', 'Retail prices have gone up slightly.', 'ราคาขายปลีกปรับตัวสูงขึ้นเล็กน้อย'),
        ('Stake', 'สเตค', 'ส่วนได้ส่วนเสีย', 'Noun', 'He holds a 20% stake in the business.', 'เขาถือหุ้น 20% ในธุรกิจนี้'),
        ('Tariff', 'ทาร์-ริฟ', 'ภาษีศุลกากร', 'Noun', 'New tariffs on imported goods were introduced.', 'มีการนำอัตราภาษีใหม่สำหรับสินค้านำเข้ามาใช้'),
        ('Utility', 'ยู-ทิล-ลิ-ตี', 'สาธารณูปโภค', 'Noun', 'The utility bills include water and electricity.', 'ค่าสาธารณูปโภคครอบคลุมค่าน้ำและค่าไฟฟ้า'),
        ('Vendor', 'เวน-ดอร์', 'ผู้จัดจำหน่าย', 'Noun', 'We need to select a reliable software vendor.', 'เราจำเป็นต้องเลือกผู้จัดจำหน่ายซอฟต์แวร์ที่เชื่อถือได้'),
        ('Wholesale', 'โฮล-เซล', 'ขายส่ง', 'Noun', 'We buy materials at wholesale prices.', 'เราซื้อวัสดุในราคาขายส่ง'),
        ('Yield', 'ยิลด์', 'ผลตอบแทน', 'Noun', 'The investment offers a high yield.', 'การลงทุนให้ผลตอบแทนสูง'),
        ('Approve', 'แอพ-พรูฟ', 'อนุมัติ', 'Verb', 'The manager approved the budget request.', 'ผู้จัดการอนุมัติคำของบประมาณ'),
        ('Bankrupt', 'แบง-ครัปท์', 'ล้มละลาย', 'Adjective', 'The company went bankrupt last year.', 'บริษัทล้มละลายเมื่อปีที่แล้ว'),
        ('Compensation', 'คอม-เพน-เซ-ชัน', 'ค่าตอบแทน', 'Noun', 'He received workers\' compensation for his injury.', 'เขาได้รับค่าตอบแทนสำหรับคนงานจากการบาดเจ็บ'),
        ('Distribute', 'ดิส-ทริ-บิวท์', 'แจกจ่าย', 'Verb', 'We distribute products worldwide.', 'เราจัดจำหน่ายสินค้าไปทั่วโลก'),
        ('Entrepreneur', 'ออน-เทรอ-เพรอ-เนอร์', 'ผู้ประกอบการ', 'Noun', 'She is a successful entrepreneur in the tech industry.', 'เธอเป็นผู้ประกอบการที่ประสบความสำเร็จในอุตสาหกรรมเทคโนโลยี'),
        ('Feature', 'ฟี-เจอร์', 'คุณลักษณะเด่น', 'Noun', 'The new car has many advanced safety features.', 'รถยนต์รุ่นใหม่มีคุณลักษณะด้านความปลอดภัยขั้นสูงมากมาย'),
        ('Guarantee', 'แก-รัน-ตี', 'การรับประกัน', 'Noun', 'The television comes with a two-year guarantee.', 'โทรทัศน์มาพร้อมกับการรับประกันสองปี'),
        ('Hierarchical', 'ไฮ-รา-คิ-คัล', 'ตามลำดับชั้น', 'Adjective', 'The organization has a hierarchical structure.', 'องค์กรมีโครงสร้างตามลำดับชั้น'),
        ('Incentive', 'อิน-เซน-ทิฟ', 'สิ่งจูงใจ', 'Noun', 'Employees are given financial incentives for good performance.', 'พนักงานจะได้รับสิ่งจูงใจทางการเงินสำหรับผลการทำงานที่ดี'),
        ('Justify', 'จัส-ติ-ไฟ', 'แสดงเหตุผล', 'Verb', 'You must justify your business expenses.', 'คุณต้องแสดงเหตุผลสำหรับค่าใช้จ่ายทางธุรกิจของคุณ'),
        ('Launch', 'ลอนช์', 'เปิดตัว', 'Verb', 'The marketing team will launch the campaign next week.', 'ทีมการตลาดจะเปิดตัวแคมเปญในสัปดาห์หน้า'),
        ('Merger', 'เมอร์-เจอร์', 'การควบรวมกิจการ', 'Noun', 'The merger between the two banks was successful.', 'การควบรวมกิจการระหว่างสองธนาคารประสบความสำเร็จ'),
        ('Niche', 'นิช', 'กลุ่มเป้าหมายเฉพาะ', 'Noun', 'They found a profitable niche in the market.', 'พวกเขาพบกลุ่มเป้าหมายเฉพาะที่ทำกำไรได้ในตลาด'),
        ('Outsource', 'เอาท์-ซอร์ส', 'จัดจ้างบุคคลภายนอก', 'Verb', 'Many companies outsource their IT services.', 'บริษัทหลายแห่งจ้างบุคคลภายนอกให้บริการด้านไอที'),
        ('Portfolio', 'พอร์ต-โฟ-ลิ-โอ', 'ผลงาน/พอร์ตโฟลิโอ', 'Noun', 'The designer presented her portfolio to the client.', 'นักออกแบบนำเสนอผลงานของเธอต่อลูกค้า'),
        ('Quarterly', 'ควอร์-เตอร์-ลี', 'รายไตรมาส', 'Adjective/Adverb', 'We publish a quarterly report.', 'เราจัดพิมพ์รายงานรายไตรมาส'),
        ('Refund', 'รี-ฟันด์', 'คืนเงิน', 'Noun', 'If you are not satisfied, we will offer a full refund.', 'หากคุณไม่พอใจ เราจะคืนเงินให้เต็มจำนวน'),
        ('Sponsor', 'สปอน-เซอร์', 'ผู้สนับสนุน', 'Noun/Verb', 'The event is sponsored by local businesses.', 'กิจกรรมนี้ได้รับการสนับสนุนจากธุรกิจในท้องถิ่น'),
        ('Turnover', 'เทิร์น-โอ-เวอร์', 'อัตราการหมุนเวียน/ยอดขาย', 'Noun', 'The company has a high staff turnover rate.', 'บริษัทมีอัตราการลาออกของพนักงานสูง'),
        ('Unanimous', 'ยู-แนน-นิ-มัส', 'เป็นเอกฉันท์', 'Adjective', 'The board reached a unanimous decision.', 'คณะกรรมการมีมติเป็นเอกฉันท์'),
        ('Viable', 'ไว-อะ-เบิล', 'ทำได้จริง', 'Adjective', 'We need to find a commercially viable solution.', 'เราจำเป็นต้องหาวิธีแก้ปัญหาที่ทำกำไรได้ในเชิงพาณิชย์'),
        ('Warrant', 'วอ-แรนท์', 'รับรอง', 'Verb', 'The situation does not warrant such drastic measures.', 'สถานการณ์ไม่ได้รุนแรงถึงขั้นต้องใช้มาตรการรุนแรงเช่นนี้'),
        ('Acquisition', 'แอค-ควิ-ซิ-ชัน', 'การเข้าซื้อกิจการ', 'Noun', 'The acquisition will double our market share.', 'การเข้าซื้อกิจการจะเพิ่มส่วนแบ่งการตลาดของเราเป็นสองเท่า'),
        ('Benchmark', 'เบนช์-มาร์ค', 'เกณฑ์มาตรฐาน', 'Noun', 'This product sets a new benchmark for quality.', 'ผลิตภัณฑ์นี้สร้างเกณฑ์มาตรฐานใหม่สำหรับคุณภาพ'),
        ('Comply', 'คอม-พลาย', 'ปฏิบัติตาม', 'Verb', 'All suppliers must comply with environmental regulations.', 'ซัพพลายเออร์ทั้งหมดต้องปฏิบัติตามข้อบังคับด้านสิ่งแวดล้อม'),
        ('Diversify', 'ได-เวอร์-ซิ-ไฟ', 'ทำให้หลากหลาย', 'Verb', 'We need to diversify our product range.', 'เราจำเป็นต้องเพิ่มความหลากหลายของสายผลิตภัณฑ์')
    ],
    'toeic_speaking': [
        ('Adapt', 'อะ-แดปท์', 'ปรับตัว', 'Verb', 'We must adapt to changing market conditions.', 'เราต้องปรับตัวให้เข้ากับสภาวะตลาดที่เปลี่ยนแปลง'),
        ('Benefit', 'เบน-เน-ฟิท', 'ผลประโยชน์', 'Noun', 'The main benefit of this plan is cost savings.', 'ประโยชน์หลักของแผนนี้คือการประหยัดต้นทุน'),
        ('Conclude', 'คอน-คลูด', 'สรุป', 'Verb', 'To conclude, we need more funding.', 'โดยสรุปแล้ว เราต้องการเงินทุนเพิ่มเติม'),
        ('Determine', 'ดี-เทอร์-มิน', 'ตัดสินใจ/กำหนด', 'Verb', 'We need to determine the best approach.', 'เราจำเป็นต้องกำหนดแนวทางที่ดีที่สุด'),
        ('Essential', 'เอส-เซน-เชียล', 'จำเป็นอย่างยิ่ง', 'Adjective', 'Teamwork is essential for success.', 'การทำงานเป็นทีมเป็นสิ่งจำเป็นอย่างยิ่งสำหรับความสำเร็จ'),
        ('Focus', 'โฟ-คัส', 'มุ่งเน้น', 'Verb', 'We should focus on customer service.', 'เราควรมุ่งเน้นไปที่การบริการลูกค้า'),
        ('Guideline', 'ไกด์-ไลน์', 'แนวทาง', 'Noun', 'Please follow the safety guidelines.', 'โปรดปฏิบัติตามแนวทางด้านความปลอดภัย'),
        ('Highlight', 'ไฮ-ไลท์', 'เน้นให้เห็นชัด', 'Verb', 'I would like to highlight three main issues.', 'ฉันต้องการเน้นให้เห็นประเด็นหลักสามประการ'),
        ('Inform', 'อิน-ฟอร์ม', 'แจ้งให้ทราบ', 'Verb', 'Please inform the staff about the meeting.', 'โปรดแจ้งให้พนักงานทราบเกี่ยวกับการประชุม'),
        ('Justify', 'จัส-ติ-ไฟ', 'อธิบายเหตุผล', 'Verb', 'Can you justify this expense?', 'คุณอธิบายเหตุผลของค่าใช้จ่ายนี้ได้ไหม?'),
        ('Knowledge', 'นอล-เลจ', 'ความรู้', 'Noun', 'He has extensive knowledge of the subject.', 'เขามีความรู้อย่างกว้างขวางในเรื่องนี้'),
        ('Locate', 'โล-เคท', 'ตั้งอยู่/หาตำแหน่ง', 'Verb', 'We are trying to locate the missing package.', 'เรากำลังพยายามค้นหาพัสดุที่หายไป'),
        ('Maximize', 'แมก-ซิ-ไมซ์', 'ทำให้สูงสุด', 'Verb', 'Our goal is to maximize efficiency.', 'เป้าหมายของเราคือการทำให้ประสิทธิภาพสูงสุด'),
        ('Note', 'โน้ท', 'สังเกต/จดจำ', 'Verb', 'Please note that the deadline has changed.', 'โปรดทราบว่ากำหนดส่งได้เปลี่ยนแปลงแล้ว'),
        ('Outline', 'เอาท์-ไลน์', 'เค้าโครง/สรุปคร่าวๆ', 'Verb/Noun', 'I will outline the marketing strategy.', 'ฉันจะสรุปโครงร่างกลยุทธ์การตลาด'),
        ('Persuade', 'เพอร์-สเวด', 'โน้มน้าว', 'Verb', 'We need to persuade the client to sign.', 'เราต้องโน้มน้าวให้ลูกค้าเซ็นสัญญา'),
        ('Question', 'เควส-ชัน', 'ตั้งคำถาม', 'Verb/Noun', 'I have a question about the budget.', 'ฉันมีคำถามเกี่ยวกับงบประมาณ'),
        ('Recognize', 'เรค-คอก-ไนซ์', 'ตระหนัก/จดจำได้', 'Verb', 'We must recognize the importance of this task.', 'เราต้องตระหนักถึงความสำคัญของงานนี้'),
        ('Summarize', 'ซัม-มะ-ไรซ์', 'สรุป', 'Verb', 'Let me summarize what we discussed.', 'ให้ฉันสรุปสิ่งที่เราได้หารือกัน'),
        ('Target', 'ทาร์-เกท', 'เป้าหมาย', 'Noun', 'Our target audience is young adults.', 'กลุ่มเป้าหมายของเราคือคนหนุ่มสาว'),
        ('Understand', 'อัน-เดอร์-สแตนด์', 'เข้าใจ', 'Verb', 'Do you understand the instructions?', 'คุณเข้าใจคำแนะนำไหม?'),
        ('Verify', 'เว-ริ-ไฟ', 'ยืนยันความถูกต้อง', 'Verb', 'Can you verify these numbers?', 'คุณช่วยยืนยันตัวเลขเหล่านี้ได้ไหม?'),
        ('Welcome', 'เวล-คัม', 'ยินดีต้อนรับ', 'Verb', 'We welcome your suggestions.', 'เรายินดีรับข้อเสนอแนะของคุณ'),
        ('Yield', 'ยิลด์', 'ยอมแพ้/ให้ผล', 'Verb', 'We will not yield to their demands.', 'เราจะไม่ยอมแพ้ต่อข้อเรียกร้องของพวกเขา'),
        ('Analyze', 'แอน-นะ-ไลซ์', 'วิเคราะห์', 'Verb', 'Let\'s analyze the sales data.', 'มาวิเคราะห์ข้อมูลการขายกันเถอะ'),
        ('Brainstorm', 'เบรน-สตอร์ม', 'ระดมสมอง', 'Verb', 'We need to brainstorm some new ideas.', 'เราจำเป็นต้องระดมสมองคิดไอเดียใหม่ๆ'),
        ('Clarify', 'แคล-ริ-ไฟ', 'อธิบายให้กระจ่าง', 'Verb', 'Could you clarify the last point?', 'คุณช่วยอธิบายประเด็นสุดท้ายให้กระจ่างได้ไหม?'),
        ('Demonstrate', 'เดม-มอน-สเตรท', 'แสดงให้เห็น', 'Verb', 'I will demonstrate how to use the software.', 'ฉันจะสาธิตวิธีใช้ซอฟต์แวร์'),
        ('Evaluate', 'อี-แวล-ลู-เอท', 'ประเมิน', 'Verb', 'We must evaluate all the options.', 'เราต้องประเมินทางเลือกทั้งหมด'),
        ('Facilitate', 'ฟา-ซิล-ลิ-เทท', 'ทำให้ง่ายขึ้น/อำนวยความสะดวก', 'Verb', 'I will facilitate the workshop tomorrow.', 'ฉันจะเป็นผู้อำนวยความสะดวกในการประชุมเชิงปฏิบัติการพรุ่งนี้'),
        ('Generate', 'เจน-เนอ-เรท', 'สร้าง/ผลิต', 'Verb', 'The campaign should generate more leads.', 'แคมเปญควรจะสร้างลูกค้าเป้าหมายได้มากขึ้น'),
        ('Handle', 'แฮน-เดิล', 'รับมือ/จัดการ', 'Verb', 'How should we handle this complaint?', 'เราควรรับมือกับข้อร้องเรียนนี้อย่างไร?'),
        ('Implement', 'อิม-พลิ-เมนท์', 'นำไปปฏิบัติ', 'Verb', 'We plan to implement the changes next week.', 'เราวางแผนที่จะนำการเปลี่ยนแปลงไปใช้ในสัปดาห์หน้า'),
        ('Judge', 'จัจ', 'ตัดสิน', 'Verb', 'It is hard to judge the outcome right now.', 'เป็นการยากที่จะตัดสินผลลัพธ์ในตอนนี้'),
        ('Keep', 'คีพ', 'รักษาไว้', 'Verb', 'Please keep me updated on the progress.', 'โปรดแจ้งให้ฉันทราบถึงความคืบหน้า'),
        ('Lead', 'ลีด', 'นำ/เป็นผู้นำ', 'Verb', 'Who will lead the project team?', 'ใครจะเป็นผู้นำทีมโครงการ?'),
        ('Manage', 'แมน-เนจ', 'จัดการ', 'Verb', 'She manages a team of 10 people.', 'เธอจัดการทีมงาน 10 คน'),
        ('Negotiate', 'นิ-โก-ชี-เอท', 'เจรจา', 'Verb', 'We are currently negotiating the contract.', 'เรากำลังอยู่ในระหว่างการเจรจาสัญญา'),
        ('Organize', 'ออร์-กา-ไนซ์', 'จัดระเบียบ/จัดเตรียม', 'Verb', 'I will organize the files.', 'ฉันจะจัดระเบียบไฟล์ต่างๆ'),
        ('Present', 'พรี-เซนต์', 'นำเสนอ', 'Verb', 'I am ready to present my findings.', 'ฉันพร้อมที่จะนำเสนอผลการค้นพบของฉันแล้ว'),
        ('Quantify', 'ควอน-ทิ-ไฟ', 'วัดปริมาณ', 'Verb', 'It is difficult to quantify the benefits.', 'เป็นการยากที่จะระบุจำนวนผลประโยชน์ออกมาเป็นตัวเลข'),
        ('Review', 'รี-วิว', 'ทบทวน', 'Verb', 'Let\'s review the document together.', 'มาทบทวนเอกสารด้วยกันเถอะ'),
        ('Support', 'ซัพ-พอร์ต', 'สนับสนุน', 'Verb', 'I fully support your decision.', 'ฉันสนับสนุนการตัดสินใจของคุณอย่างเต็มที่'),
        ('Tackle', 'แทค-เคิล', 'รับมือกับ(ปัญหา)', 'Verb', 'We need to tackle this problem immediately.', 'เราจำเป็นต้องรับมือกับปัญหานี้ทันที'),
        ('Urge', 'เอิร์จ', 'กระตุ้น/เร่งเร้า', 'Verb', 'I urge you to consider this option.', 'ฉันขอร้องให้คุณพิจารณาทางเลือกนี้'),
        ('Value', 'แวล-ลู', 'ให้คุณค่า', 'Verb', 'We value your feedback.', 'เราให้คุณค่ากับความคิดเห็นของคุณ'),
        ('Weigh', 'เวย์', 'ชั่งน้ำหนัก(พิจารณา)', 'Verb', 'We must weigh the pros and cons.', 'เราต้องชั่งน้ำหนักข้อดีข้อเสีย'),
        ('Examine', 'เอ็ก-แซม-มิน', 'ตรวจสอบ', 'Verb', 'We will examine the issue closely.', 'เราจะตรวจสอบปัญหาอย่างใกล้ชิด'),
        ('Yield', 'ยิลด์', 'ยอมทำตาม', 'Verb', 'We cannot yield to pressure.', 'เราไม่สามารถยอมแพ้ต่อแรงกดดันได้'),
        ('Zero', 'ซี-โร', 'ศูนย์/ปรับศูนย์', 'Verb', 'Let\'s zero in on the main problem.', 'มาเจาะจงที่ปัญหาหลักกันเถอะ')
    ],
    'toefl_listening': [
        ('Astronomy', 'แอส-ตรอ-โน-มี', 'ดาราศาสตร์', 'Noun', 'The lecture on astronomy was fascinating.', 'การบรรยายเรื่องดาราศาสตร์น่าสนใจมาก'),
        ('Biology', 'ไบ-ออล-โล-จี', 'ชีววิทยา', 'Noun', 'She is majoring in marine biology.', 'เธอเรียนวิชาเอกชีววิทยาทางทะเล'),
        ('Chemistry', 'เค-มิส-ทรี', 'เคมี', 'Noun', 'The chemistry lab is on the second floor.', 'ห้องปฏิบัติการเคมีอยู่บนชั้นสอง'),
        ('Documentary', 'ดอค-คิว-เมน-ทา-รี', 'สารคดี', 'Noun', 'We watched a documentary about climate change.', 'เราดูสารคดีเกี่ยวกับการเปลี่ยนแปลงสภาพภูมิอากาศ'),
        ('Ecology', 'อี-คอล-โล-จี', 'นิเวศวิทยา', 'Noun', 'Ecology studies how organisms interact.', 'นิเวศวิทยาศึกษาว่าสิ่งมีชีวิตมีปฏิสัมพันธ์กันอย่างไร'),
        ('Fossil', 'ฟอส-ซิล', 'ฟอสซิล/ซากดึกดำบรรพ์', 'Noun', 'They found a dinosaur fossil in the desert.', 'พวกเขาพบซากฟอสซิลไดโนเสาร์ในทะเลทราย'),
        ('Geology', 'จี-ออล-โล-จี', 'ธรณีวิทยา', 'Noun', 'Geology is the study of the Earth.', 'ธรณีวิทยาคือการศึกษาเกี่ยวกับโลก'),
        ('Habitat', 'แฮบ-บิ-แทท', 'ถิ่นที่อยู่', 'Noun', 'The destruction of their natural habitat is a problem.', 'การทำลายถิ่นที่อยู่ตามธรรมชาติของพวกมันเป็นปัญหา'),
        ('Institution', 'อิน-สติ-ทิว-ชัน', 'สถาบัน', 'Noun', 'Harvard is a prestigious academic institution.', 'ฮาร์วาร์ดเป็นสถาบันการศึกษาที่มีชื่อเสียง'),
        ('Journalism', 'เจอร์-นัล-ลิส-ซึม', 'วารสารศาสตร์', 'Noun', 'He is studying journalism at university.', 'เขากำลังศึกษาวารสารศาสตร์ที่มหาวิทยาลัย'),
        ('Kinetic', 'คิ-เน-ติค', 'จลน์(เกี่ยวกับพลังงานการเคลื่อนที่)', 'Adjective', 'The professor explained kinetic energy.', 'ศาสตราจารย์อธิบายเรื่องพลังงานจลน์'),
        ('Linguistics', 'ลิง-กวิส-ติคส์', 'ภาษาศาสตร์', 'Noun', 'Linguistics is the scientific study of language.', 'ภาษาศาสตร์คือการศึกษาภาษาในเชิงวิทยาศาสตร์'),
        ('Meteorology', 'มี-ที-ออ-รอล-โล-จี', 'อุตุนิยมวิทยา', 'Noun', 'Meteorology helps us predict the weather.', 'อุตุนิยมวิทยาช่วยให้เราพยากรณ์อากาศได้'),
        ('Neanderthal', 'นี-แอน-เดอร์-ธัล', 'มนุษย์นีแอนเดอร์ทัล', 'Noun', 'Neanderthals lived in Europe long ago.', 'มนุษย์นีแอนเดอร์ทัลเคยอาศัยอยู่ในยุโรปเมื่อนานมาแล้ว'),
        ('Organism', 'ออร์-กา-นิส-ซึม', 'สิ่งมีชีวิต', 'Noun', 'Microscopic organisms are found in water.', 'พบสิ่งมีชีวิตขนาดเล็กในน้ำ'),
        ('Psychology', 'ไซ-คอล-โล-จี', 'จิตวิทยา', 'Noun', 'Psychology studies the human mind and behavior.', 'จิตวิทยาศึกษาจิตใจและพฤติกรรมของมนุษย์'),
        ('Quotient', 'โคว-เชียนท์', 'ผลหาร/ระดับ(เช่น IQ)', 'Noun', 'Intelligence quotient is commonly known as IQ.', 'Intelligence quotient เป็นที่รู้จักกันทั่วไปในชื่อ IQ'),
        ('Radiation', 'เร-ดิ-เอ-ชัน', 'การแผ่รังสี', 'Noun', 'Exposure to high levels of radiation is dangerous.', 'การสัมผัสกับรังสีในระดับสูงเป็นอันตราย'),
        ('Sociology', 'โซ-ซิ-ออล-โล-จี', 'สังคมวิทยา', 'Noun', 'Sociology focuses on human social relationships.', 'สังคมวิทยามุ่งเน้นไปที่ความสัมพันธ์ทางสังคมของมนุษย์'),
        ('Tectonic', 'เทค-ทอน-นิค', 'เกี่ยวกับการแปรสัณฐานเปลือกโลก', 'Adjective', 'Earthquakes are caused by tectonic plate movement.', 'แผ่นดินไหวเกิดจากการเคลื่อนตัวของแผ่นเปลือกโลก'),
        ('Universe', 'ยู-นิ-เวิร์ส', 'จักรวาล', 'Noun', 'The universe is constantly expanding.', 'จักรวาลกำลังขยายตัวอย่างต่อเนื่อง'),
        ('Volcano', 'โวล-เค-โน', 'ภูเขาไฟ', 'Noun', 'The volcano erupted last night.', 'ภูเขาไฟปะทุเมื่อคืนนี้'),
        ('Zoology', 'ซู-ออล-โล-จี', 'สัตววิทยา', 'Noun', 'Zoology is the scientific study of animals.', 'สัตววิทยาคือการศึกษาสัตว์ในเชิงวิทยาศาสตร์'),
        ('Abstract', 'แอ็บ-สแทรคท์', 'บทคัดย่อ/นามธรรม', 'Noun/Adjective', 'Read the abstract before the full article.', 'อ่านบทคัดย่อก่อนอ่านบทความเต็ม'),
        ('Botany', 'บอท-ทา-นี', 'พฤกษศาสตร์', 'Noun', 'Botany is a branch of biology focusing on plants.', 'พฤกษศาสตร์เป็นสาขาหนึ่งของชีววิทยาที่เน้นเรื่องพืช'),
        ('Chronological', 'โคร-โน-ลอ-จิ-คัล', 'ตามลำดับเวลา', 'Adjective', 'The events are listed in chronological order.', 'เหตุการณ์ต่างๆ ถูกแสดงตามลำดับเวลา'),
        ('Deduce', 'ดี-ดิวส์', 'สรุปจากหลักฐาน', 'Verb', 'We can deduce the age of the tree from its rings.', 'เราสามารถอนุมานอายุของต้นไม้ได้จากวงปีของมัน'),
        ('Empirical', 'เอ็ม-พิ-ริ-คัล', 'เชิงประจักษ์/จากการทดลอง', 'Adjective', 'There is no empirical evidence to support this.', 'ไม่มีหลักฐานเชิงประจักษ์ใดมารองรับเรื่องนี้'),
        ('Fluctuation', 'ฟลัค-ชู-เอ-ชัน', 'ความผันผวน', 'Noun', 'There is a natural fluctuation in temperature.', 'มีความผันผวนของอุณหภูมิตามธรรมชาติ'),
        ('Genetics', 'เจ-เน-ติคส์', 'พันธุศาสตร์', 'Noun', 'Genetics plays a role in many diseases.', 'พันธุศาสตร์มีบทบาทในหลายโรค'),
        ('Herbivore', 'เฮอร์-บิ-วอร์', 'สัตว์กินพืช', 'Noun', 'Cows and horses are herbivores.', 'วัวและม้าเป็นสัตว์กินพืช'),
        ('Implication', 'อิม-พลิ-เค-ชัน', 'ความหมายแฝง/ผลที่ตามมา', 'Noun', 'What are the implications of this discovery?', 'ผลกระทบจากการค้นพบนี้คืออะไร?'),
        ('Justification', 'จัส-ติ-ฟิ-เค-ชัน', 'การให้เหตุผล', 'Noun', 'There is no justification for his actions.', 'ไม่มีข้อแก้ตัวใดๆ สำหรับการกระทำของเขา'),
        ('Kinetics', 'คิ-เน-ติคส์', 'จลนศาสตร์', 'Noun', 'We studied the kinetics of chemical reactions.', 'เราศึกษาจลนศาสตร์ของปฏิกิริยาเคมี'),
        ('Lunar', 'ลู-นาร์', 'เกี่ยวกับดวงจันทร์', 'Adjective', 'A lunar eclipse occurs when the Earth blocks the sun.', 'จันทรุปราคาเกิดขึ้นเมื่อโลกบังดวงอาทิตย์'),
        ('Migration', 'ไม-เกร-ชัน', 'การอพยพ', 'Noun', 'Bird migration happens every autumn.', 'การอพยพของนกเกิดขึ้นทุกฤดูใบไม้ร่วง'),
        ('Nutrient', 'นิว-เทรียนท์', 'สารอาหาร', 'Noun', 'Plants absorb nutrients from the soil.', 'พืชดูดซับสารอาหารจากดิน'),
        ('Observation', 'ออบ-เซิร์ฟ-เว-ชัน', 'การสังเกตการณ์', 'Noun', 'Careful observation is key to science.', 'การสังเกตอย่างระมัดระวังเป็นกุญแจสำคัญของวิทยาศาสตร์'),
        ('Predator', 'พรี-เด-เตอร์', 'สัตว์นักล่า', 'Noun', 'Lions are apex predators.', 'สิงโตเป็นนักล่าจุดสูงสุด'),
        ('Quantitative', 'ควอน-ทิ-เท-ทิฟ', 'เชิงปริมาณ', 'Adjective', 'The study uses quantitative research methods.', 'การศึกษาใช้วิธีการวิจัยเชิงปริมาณ'),
        ('Reptile', 'เรป-ไทล์', 'สัตว์เลื้อยคลาน', 'Noun', 'Snakes and lizards are reptiles.', 'งูและกิ้งก่าเป็นสัตว์เลื้อยคลาน'),
        ('Species', 'สปี-ชีส์', 'สายพันธุ์', 'Noun', 'There are thousands of species of spiders.', 'มีแมงมุมหลายพันสายพันธุ์'),
        ('Thermodynamics', 'เธอร์-โม-ได-นาม-มิคส์', 'อุณหพลศาสตร์', 'Noun', 'The second law of thermodynamics is complex.', 'กฎข้อที่สองของอุณหพลศาสตร์มีความซับซ้อน'),
        ('Unprecedented', 'อัน-พรี-เซ-เดนท์-เท็ด', 'ไม่เคยเกิดขึ้นมาก่อน', 'Adjective', 'This level of growth is unprecedented.', 'ระดับการเติบโตนี้ไม่เคยมีมาก่อน'),
        ('Variable', 'แว-ริ-อะ-เบิล', 'ตัวแปร', 'Noun', 'Temperature is a key variable in this experiment.', 'อุณหภูมิเป็นตัวแปรสำคัญในการทดลองนี้'),
        ('Wavelength', 'เวฟ-เลงธ์', 'ความยาวคลื่น', 'Noun', 'Red light has a longer wavelength than blue light.', 'แสงสีแดงมีความยาวคลื่นมากกว่าแสงสีน้ำเงิน'),
        ('X-ray', 'เอกซ์-เรย์', 'รังสีเอกซ์', 'Noun', 'X-rays are used to see inside the body.', 'รังสีเอกซ์ใช้เพื่อดูภายในร่างกาย'),
        ('Yield', 'ยิลด์', 'ผลผลิต(ทางการเกษตร)', 'Noun', 'The crop yield was lower than expected.', 'ผลผลิตทางการเกษตรต่ำกว่าที่คาดไว้'),
        ('Zone', 'โซน', 'เขต/พื้นที่', 'Noun', 'The area is a protected ecological zone.', 'พื้นที่นี้เป็นเขตนิเวศวิทยาที่ได้รับการคุ้มครอง'),
        ('Aquatic', 'อะ-ควา-ติค', 'เกี่ยวกับน้ำ', 'Adjective', 'Whales are aquatic mammals.', 'ปลาวาฬเป็นสัตว์เลี้ยงลูกด้วยนมในน้ำ')
    ],
    'toefl_reading': [
        ('Aesthetic', 'เอส-เธ-ติค', 'เกี่ยวกับความงาม', 'Adjective', 'The building has great aesthetic appeal.', 'อาคารนี้มีความดึงดูดใจด้านสุนทรียภาพอย่างมาก'),
        ('Bizarre', 'บิ-ซาร์', 'แปลกประหลาด', 'Adjective', 'The story was completely bizarre.', 'เรื่องราวนั้นแปลกประหลาดอย่างสิ้นเชิง'),
        ('Coincide', 'โค-อิน-ไซด์', 'เกิดขึ้นพร้อมกัน', 'Verb', 'Her arrival coincided with the storm.', 'การมาถึงของเธอเกิดขึ้นพร้อมกับพายุ'),
        ('Deviate', 'ดี-วิ-เอท', 'เบี่ยงเบน', 'Verb', 'Never deviate from the original plan.', 'อย่าเบี่ยงเบนไปจากแผนเดิม'),
        ('Elicit', 'อี-ลิส-ซิท', 'ดึงออกมา/ล้วงความลับ', 'Verb', 'The question elicited a defensive response.', 'คำถามนั้นกระตุ้นให้เกิดการตอบสนองเชิงป้องกันตัว'),
        ('Fluctuate', 'ฟลัค-ชู-เอท', 'ผันผวน', 'Verb', 'Prices fluctuate based on supply and demand.', 'ราคาผันผวนตามอุปสงค์และอุปทาน'),
        ('Gregarious', 'กริ-กา-เรียส', 'ชอบเข้าสังคม', 'Adjective', 'Dolphins are gregarious animals.', 'โลมาเป็นสัตว์ที่ชอบอยู่รวมฝูง'),
        ('Hinder', 'ฮิน-เดอร์', 'ขัดขวาง', 'Verb', 'Lack of funding will hinder the project.', 'การขาดแคลนเงินทุนจะขัดขวางโครงการ'),
        ('Innate', 'อิน-เนท', 'โดยกำเนิด', 'Adjective', 'Birds have an innate ability to fly.', 'นกมีความสามารถในการบินโดยกำเนิด'),
        ('Juxtapose', 'จัค-สตา-โพส', 'วางเคียงกันเพื่อเปรียบเทียบ', 'Verb', 'The artist juxtaposes bright colors with dark ones.', 'ศิลปินนำสีสว่างมาวางคู่กับสีเข้มเพื่อเปรียบเทียบ'),
        ('Lethal', 'ลี-ธัล', 'ถึงตาย', 'Adjective', 'The snake has a lethal bite.', 'งูตัวนี้มีพิษกัดถึงตาย'),
        ('Meticulous', 'เม-ทิค-คิว-ลัส', 'พิถีพิถัน', 'Adjective', 'He is very meticulous about his work.', 'เขาพิถีพิถันกับการทำงานมาก'),
        ('Nomad', 'โน-แมด', 'คนพเนจร', 'Noun', 'Nomads move from place to place.', 'คนเร่ร่อนย้ายจากที่หนึ่งไปยังอีกที่หนึ่ง'),
        ('Obsolete', 'ออบ-โซ-ลีท', 'ล้าสมัย', 'Adjective', 'Typewriters are largely obsolete.', 'เครื่องพิมพ์ดีดส่วนใหญ่ล้าสมัยแล้ว'),
        ('Paradox', 'พา-รา-ดอกซ์', 'ความขัดแย้งในตัวเอง', 'Noun', 'It is a paradox that technology makes us more isolated.', 'เป็นเรื่องย้อนแย้งที่เทคโนโลยีทำให้เราโดดเดี่ยวมากขึ้น'),
        ('Qualitative', 'ควอล-ลิ-เท-ทิฟ', 'เชิงคุณภาพ', 'Adjective', 'We need a qualitative analysis of the data.', 'เราต้องการการวิเคราะห์ข้อมูลในเชิงคุณภาพ'),
        ('Redundant', 'รี-ดัน-ดันท์', 'ซ้ำซ้อน', 'Adjective', 'The second paragraph is redundant.', 'ย่อหน้าที่สองมีความซ้ำซ้อน'),
        ('Skeptical', 'สเคป-ติ-คัล', 'สงสัย/ไม่เชื่อ', 'Adjective', 'I am skeptical of his claims.', 'ฉันยังคงคลางแคลงใจในคำกล่าวอ้างของเขา'),
        ('Tangible', 'แทน-จิ-เบิล', 'จับต้องได้/ชัดเจน', 'Adjective', 'We need tangible evidence.', 'เราต้องการหลักฐานที่จับต้องได้'),
        ('Ubiquitous', 'ยู-บิค-ควิ-ตัส', 'มีอยู่ทุกหนทุกแห่ง', 'Adjective', 'Mobile phones are ubiquitous today.', 'โทรศัพท์มือถือมีอยู่ทุกหนทุกแห่งในปัจจุบัน'),
        ('Vacillate', 'วา-ซิล-เลท', 'ลังเล', 'Verb', 'He vacillated between two choices.', 'เขาลังเลระหว่างสองตัวเลือก'),
        ('Warrant', 'วอ-แรนท์', 'รับรอง/เป็นเหตุผลสมควร', 'Verb', 'The evidence does not warrant a trial.', 'หลักฐานไม่มีน้ำหนักพอที่จะนำไปสู่การพิจารณาคดี'),
        ('Alleviate', 'อัล-ลี-วิ-เอท', 'บรรเทา', 'Verb', 'The medicine will alleviate your pain.', 'ยาจะช่วยบรรเทาอาการปวดของคุณ'),
        ('Benevolent', 'บิ-เนฟ-โว-เลนท์', 'เมตตา', 'Adjective', 'He was a benevolent leader.', 'เขาเป็นผู้นำที่มีความเมตตา'),
        ('Candid', 'แคน-ดิด', 'ตรงไปตรงมา', 'Adjective', 'She gave a candid interview.', 'เธอให้สัมภาษณ์อย่างตรงไปตรงมา'),
        ('Deter', 'ดี-เทอร์', 'ขัดขวาง/ยับยั้ง', 'Verb', 'High prices will deter buyers.', 'ราคาสูงจะขัดขวางผู้ซื้อ'),
        ('Elucidate', 'อิล-ลู-ซิ-เดท', 'อธิบายให้กระจ่าง', 'Verb', 'Please elucidate your point further.', 'โปรดอธิบายประเด็นของคุณให้กระจ่างยิ่งขึ้น'),
        ('Frivolous', 'ฟริ-โว-ลัส', 'ไม่เอาจริงเอาจัง/ไร้สาระ', 'Adjective', 'Do not waste time on frivolous lawsuits.', 'อย่าเสียเวลากับคดีฟ้องร้องที่ไร้สาระ'),
        ('Gullible', 'กัล-ลิ-เบิล', 'หลอกง่าย', 'Adjective', 'The gullible tourists paid too much.', 'นักท่องเที่ยวที่หลอกง่ายจ่ายเงินแพงเกินไป'),
        ('Homogeneous', 'โฮ-โม-จี-เนียส', 'เป็นเนื้อเดียวกัน', 'Adjective', 'Japan is a largely homogeneous society.', 'ญี่ปุ่นเป็นสังคมที่มีความกลมกลืนเป็นเนื้อเดียวกันสูง'),
        ('Impending', 'อิม-เพน-ดิง', 'ใกล้เข้ามา', 'Adjective', 'They braced for the impending storm.', 'พวกเขาเตรียมพร้อมรับมือพายุที่กำลังใกล้เข้ามา'),
        ('Jeopardize', 'เจพ-พาร์-ไดซ์', 'เป็นอันตรายต่อ', 'Verb', 'His actions could jeopardize the mission.', 'การกระทำของเขาอาจทำให้ภารกิจตกอยู่ในอันตรายได้'),
        ('Lucrative', 'ลู-ครา-ทิฟ', 'ทำกำไรได้ดี', 'Adjective', 'Real estate can be a lucrative business.', 'อสังหาริมทรัพย์สามารถเป็นธุรกิจที่ทำกำไรได้ดี'),
        ('Mitigate', 'มิท-ทิ-เกท', 'บรรเทา(ความรุนแรง)', 'Verb', 'We must take steps to mitigate the risks.', 'เราต้องดำเนินการเพื่อบรรเทาความเสี่ยง'),
        ('Nostalgia', 'นอส-ตัล-เจีย', 'ความหวนหาอดีต', 'Noun', 'Listening to that song brings back nostalgia.', 'การฟังเพลงนั้นทำให้รู้สึกคิดถึงอดีต'),
        ('Opaque', 'โอ-เพค', 'ทึบแสง/เข้าใจยาก', 'Adjective', 'The glass is opaque, so you cannot see through it.', 'กระจกนั้นทึบแสง คุณจึงไม่สามารถมองทะลุผ่านได้'),
        ('Pragmatic', 'แพรก-แมท-ติค', 'เน้นการปฏิบัติจริง', 'Adjective', 'We need a pragmatic solution to this problem.', 'เราต้องการวิธีการแก้ปัญหานี้ในเชิงปฏิบัติ'),
        ('Quaint', 'เควนท์', 'น่ารักแบบโบราณ', 'Adjective', 'They visited a quaint little village.', 'พวกเขาไปเยี่ยมชมหมู่บ้านเล็กๆ ที่ดูแปลกตาน่ารัก'),
        ('Resilient', 'รี-ซิล-เลียนท์', 'ฟื้นตัวได้เร็ว/ยืดหยุ่น', 'Adjective', 'The economy has proven to be resilient.', 'เศรษฐกิจได้พิสูจน์ให้เห็นแล้วว่ามีความยืดหยุ่น'),
        ('Scrutinize', 'สครู-ทิ-ไนซ์', 'พิจารณาอย่างละเอียด', 'Verb', 'The committee will scrutinize the documents.', 'คณะกรรมการจะตรวจสอบเอกสารอย่างละเอียด'),
        ('Tenacious', 'เท-เน-เชียส', 'ดื้อดึง/เหนียวแน่น', 'Adjective', 'She is a tenacious advocate for animal rights.', 'เธอเป็นผู้สนับสนุนสิทธิสัตว์อย่างเหนียวแน่น'),
        ('Unambiguous', 'อัน-แอม-บิก-กิว-อัส', 'ชัดเจน/ไม่กำกวม', 'Adjective', 'The rules are unambiguous.', 'กฎระเบียบมีความชัดเจนไม่กำกวม'),
        ('Vindicate', 'วิน-ดิ-เคท', 'พิสูจน์ความบริสุทธิ์', 'Verb', 'The DNA evidence vindicated him.', 'หลักฐานดีเอ็นเอพิสูจน์ความบริสุทธิ์ของเขา'),
        ('Abundant', 'อะ-บัน-ดันท์', 'มากมายอุดมสมบูรณ์', 'Adjective', 'There is an abundant supply of fresh water.', 'มีแหล่งน้ำจืดที่อุดมสมบูรณ์'),
        ('Coherent', 'โค-เฮีย-เรนท์', 'สอดคล้องกัน/มีเหตุผล', 'Adjective', 'His explanation was not coherent.', 'คำอธิบายของเขาไม่สอดคล้องและไม่มีเหตุผล'),
        ('Didactic', 'ได-แดค-ติค', 'สั่งสอน', 'Adjective', 'The story has a didactic purpose.', 'เรื่องราวมีจุดประสงค์เพื่อสั่งสอน'),
        ('Ephemeral', 'อิ-เฟม-เมอ-รัล', 'อยู่ได้ไม่นาน/ชั่วคราว', 'Adjective', 'Fame is often ephemeral.', 'ชื่อเสียงมักจะอยู่ได้ไม่นาน'),
        ('Fortuitous', 'ฟอร์-ทิว-อิ-ตัส', 'บังเอิญ(ในทางดี)', 'Adjective', 'Their meeting was entirely fortuitous.', 'การพบกันของพวกเขาเป็นเรื่องบังเอิญอย่างแท้จริง'),
        ('Hackneyed', 'แฮค-นีด', 'ซ้ำซากจำเจ', 'Adjective', 'The movie plot was somewhat hackneyed.', 'โครงเรื่องของภาพยนตร์ค่อนข้างจำเจ'),
        ('Impetuous', 'อิม-เพท-ชู-อัส', 'ใจร้อน/หุนหันพลันแล่น', 'Adjective', 'He is an impetuous young man.', 'เขาเป็นชายหนุ่มที่ใจร้อน')
    ],
    'toefl_speaking': [
        ('Acknowledge', 'แอค-นอล-เลจ', 'ยอมรับ', 'Verb', 'I acknowledge that I made a mistake.', 'ฉันยอมรับว่าฉันทำผิดพลาด'),
        ('Argue', 'อาร์-กิว', 'โต้แย้ง', 'Verb', 'Some argue that homework is unnecessary.', 'บางคนโต้แย้งว่าการบ้านเป็นสิ่งที่ไม่จำเป็น'),
        ('Assume', 'แอส-ซูม', 'สันนิษฐาน', 'Verb', 'Do not assume everything you read is true.', 'อย่าทึกทักเอาว่าทุกสิ่งที่คุณอ่านเป็นความจริง'),
        ('Claim', 'เคลม', 'กล่าวอ้าง', 'Verb/Noun', 'The author claims that technology harms us.', 'ผู้เขียนอ้างว่าเทคโนโลยีเป็นอันตรายต่อเรา'),
        ('Conclude', 'คอน-คลูด', 'สรุป', 'Verb', 'I would like to conclude by saying...', 'ฉันขอสรุปโดยกล่าวว่า...'),
        ('Criticize', 'คริ-ติ-ไซซ์', 'วิจารณ์', 'Verb', 'Many people criticize the government\'s policy.', 'ผู้คนจำนวนมากวิพากษ์วิจารณ์นโยบายของรัฐบาล'),
        ('Defend', 'ดี-เฟนด์', 'ปกป้อง/แก้ต่าง', 'Verb', 'She had to defend her thesis.', 'เธอต้องปกป้องวิทยานิพนธ์ของเธอ'),
        ('Discuss', 'ดิส-คัส', 'อภิปราย', 'Verb', 'We will discuss the pros and cons.', 'เราจะหารือเกี่ยวกับข้อดีและข้อเสีย'),
        ('Emphasize', 'เอ็ม-ฟะ-ไซซ์', 'เน้นย้ำ', 'Verb', 'I want to emphasize the importance of education.', 'ฉันต้องการเน้นย้ำถึงความสำคัญของการศึกษา'),
        ('Examine', 'เอ็ก-แซม-มิน', 'ตรวจสอบ/พิจารณา', 'Verb', 'Let us examine the facts.', 'เรามาตรวจสอบข้อเท็จจริงกันเถอะ'),
        ('Explain', 'เอ็กซ์-เพลน', 'อธิบาย', 'Verb', 'Can you explain why you disagree?', 'คุณช่วยอธิบายได้ไหมว่าทำไมคุณถึงไม่เห็นด้วย?'),
        ('Highlight', 'ไฮ-ไลท์', 'เน้นให้เห็นเด่นชัด', 'Verb', 'The report highlights the key issues.', 'รายงานเน้นย้ำถึงประเด็นสำคัญ'),
        ('Illustrate', 'อิล-ลัส-เตรท', 'ยกตัวอย่างประกอบ', 'Verb', 'I will illustrate my point with an example.', 'ฉันจะยกตัวอย่างเพื่ออธิบายประเด็นของฉัน'),
        ('Interpret', 'อิน-เทอร์-พรีท', 'ตีความ', 'Verb', 'How do you interpret this poem?', 'คุณตีความบทกวีนี้อย่างไร?'),
        ('Justify', 'จัส-ติ-ไฟ', 'แสดงเหตุผลสนับสนุน', 'Verb', 'You must justify your answer.', 'คุณต้องให้เหตุผลประกอบคำตอบของคุณ'),
        ('Maintain', 'เมน-เทน', 'ยืนกราน/รักษา', 'Verb', 'He maintains that he is innocent.', 'เขายืนกรานว่าเขาเป็นผู้บริสุทธิ์'),
        ('Mention', 'เมน-ชัน', 'กล่าวถึง', 'Verb', 'Did I mention that I have a dog?', 'ฉันเคยบอกหรือเปล่าว่าฉันมีสุนัข?'),
        ('Note', 'โน้ท', 'สังเกต/กล่าวถึง', 'Verb', 'It is important to note that times have changed.', 'สิ่งสำคัญคือต้องสังเกตว่ายุคสมัยเปลี่ยนไปแล้ว'),
        ('Observe', 'ออบ-เซิร์ฟ', 'สังเกตเห็น/ให้ความเห็น', 'Verb', 'He observed that the sky was getting dark.', 'เขาสังเกตเห็นว่าท้องฟ้าเริ่มมืดลง'),
        ('Persuade', 'เพอร์-สเวด', 'โน้มน้าว', 'Verb', 'I am trying to persuade my parents.', 'ฉันพยายามเกลี้ยกล่อมพ่อแม่ของฉัน'),
        ('Point out', 'พอยท์ เอาท์', 'ชี้ให้เห็น', 'Phrasal Verb', 'I must point out a flaw in your argument.', 'ฉันต้องชี้ให้เห็นข้อบกพร่องในข้อโต้แย้งของคุณ'),
        ('Propose', 'โปร-โพส', 'เสนอ', 'Verb', 'I propose a new solution.', 'ฉันขอเสนอวิธีแก้ปัญหาแบบใหม่'),
        ('Question', 'เควส-ชัน', 'ตั้งคำถาม', 'Verb', 'I question the validity of this study.', 'ฉันตั้งคำถามถึงความถูกต้องของการศึกษานี้'),
        ('Recognize', 'เรค-คอก-ไนซ์', 'ตระหนัก/ยอมรับ', 'Verb', 'We must recognize the danger.', 'เราต้องตระหนักถึงอันตราย'),
        ('Recommend', 'เรค-คอม-เมนด์', 'แนะนำ', 'Verb', 'I strongly recommend reading this book.', 'ฉันขอแนะนำอย่างยิ่งให้อ่านหนังสือเล่มนี้'),
        ('Refute', 'รี-ฟิวท์', 'หักล้าง(ข้อโต้แย้ง)', 'Verb', 'He failed to refute the evidence.', 'เขาล้มเหลวในการหักล้างหลักฐาน'),
        ('State', 'สเตท', 'กล่าวระบุ', 'Verb', 'The speaker stated his opinion clearly.', 'ผู้พูดแสดงความคิดเห็นอย่างชัดเจน'),
        ('Suggest', 'ซัก-เจสท์', 'เสนอแนะ', 'Verb', 'I suggest we take a different approach.', 'ฉันเสนอให้เราใช้วิธีการที่ต่างออกไป'),
        ('Summarize', 'ซัม-มะ-ไรซ์', 'สรุป', 'Verb', 'To summarize, this is a complex issue.', 'โดยสรุปแล้ว นี่เป็นปัญหาที่ซับซ้อน'),
        ('Support', 'ซัพ-พอร์ต', 'สนับสนุน', 'Verb', 'Statistics support this claim.', 'สถิติสนับสนุนคำกล่าวอ้างนี้'),
        ('Agree', 'อะ-กรี', 'เห็นด้วย', 'Verb', 'I completely agree with the speaker.', 'ฉันเห็นด้วยกับผู้พูดอย่างสมบูรณ์'),
        ('Disagree', 'ดิส-อะ-กรี', 'ไม่เห็นด้วย', 'Verb', 'I strongly disagree with that statement.', 'ฉันไม่เห็นด้วยอย่างยิ่งกับคำกล่าวนั้น'),
        ('Believe', 'บิ-ลีฟ', 'เชื่อว่า', 'Verb', 'I believe that early childhood education is vital.', 'ฉันเชื่อว่าการศึกษาปฐมวัยเป็นสิ่งสำคัญ'),
        ('Consider', 'คอน-ซิ-เดอร์', 'พิจารณา', 'Verb', 'We should consider the long-term effects.', 'เราควรพิจารณาถึงผลกระทบระยะยาว'),
        ('Compare', 'คอม-แพร์', 'เปรียบเทียบ', 'Verb', 'If we compare the two systems...', 'ถ้าเราเปรียบเทียบทั้งสองระบบ...'),
        ('Contrast', 'คอน-ทราสท์', 'เปรียบเทียบความแตกต่าง', 'Verb', 'By contrast, the new method is faster.', 'ในทางตรงกันข้าม วิธีการใหม่นั้นเร็วกว่า'),
        ('Elaborate', 'อี-แลบ-โบ-เรท', 'อธิบายเพิ่มเติม', 'Verb', 'Could you elaborate on that point?', 'คุณช่วยอธิบายประเด็นนั้นเพิ่มเติมได้ไหม?'),
        ('Specify', 'สเป-ซิ-ไฟ', 'ระบุรายละเอียด', 'Verb', 'Please specify what you need.', 'โปรดระบุรายละเอียดสิ่งที่คุณต้องการ'),
        ('Advocate', 'แอด-โว-เคท', 'สนับสนุน/ทนาย', 'Verb/Noun', 'She advocates for environmental protection.', 'เธอสนับสนุนการปกป้องสิ่งแวดล้อม'),
        ('Deny', 'ดี-นาย', 'ปฏิเสธ', 'Verb', 'The company denies any wrongdoing.', 'บริษัทปฏิเสธการกระทำผิดใดๆ'),
        ('Evaluate', 'อี-แวล-ลู-เอท', 'ประเมิน', 'Verb', 'We need to evaluate the risks carefully.', 'เราจำเป็นต้องประเมินความเสี่ยงอย่างรอบคอบ'),
        ('Forecast', 'ฟอร์-คาสท์', 'พยากรณ์', 'Verb', 'They forecast an increase in population.', 'พวกเขาคาดการณ์ว่าประชากรจะเพิ่มขึ้น'),
        ('Generalize', 'เจน-เนอ-รัล-ไลซ์', 'กล่าวสรุปทั่วๆ ไป', 'Verb', 'It is unfair to generalize about all teenagers.', 'มันไม่ยุติธรรมที่จะเหมารวมวัยรุ่นทั้งหมด'),
        ('Infer', 'อิน-เฟอร์', 'อนุมาน', 'Verb', 'What can we infer from this passage?', 'เราสามารถอนุมานอะไรได้จากข้อความนี้?'),
        ('Perceive', 'เพอร์-ซีฟ', 'รับรู้/เข้าใจ', 'Verb', 'How do people perceive this brand?', 'ผู้คนรับรู้ถึงแบรนด์นี้อย่างไร?'),
        ('Predict', 'พรี-ดิคท์', 'ทำนาย', 'Verb', 'No one can predict the future with certainty.', 'ไม่มีใครสามารถทำนายอนาคตได้อย่างแน่นอน'),
        ('Reiterate', 'รี-อิท-เทอ-เรท', 'กล่าวย้ำ', 'Verb', 'Let me reiterate my main point.', 'ฉันขอกล่าวย้ำประเด็นหลักของฉันอีกครั้ง'),
        ('Stipulate', 'สติ-พิว-เลท', 'ระบุเป็นเงื่อนไข', 'Verb', 'The contract stipulates a strict deadline.', 'สัญญาระบุเงื่อนไขกำหนดเวลาที่เข้มงวด'),
        ('Validate', 'แวล-ลิ-เดท', 'ทำให้มีผล/พิสูจน์ว่าจริง', 'Verb', 'This data validates our earlier findings.', 'ข้อมูลนี้พิสูจน์ว่าผลการค้นพบก่อนหน้านี้ของเราเป็นความจริง'),
        ('Verify', 'เว-ริ-ไฟ', 'ตรวจสอบความถูกต้อง', 'Verb', 'I need to verify this information first.', 'ฉันต้องตรวจสอบข้อมูลนี้ก่อน')
    ]
}

# Read existing vocabulary
with open('vocabulary.json', 'r', encoding='utf-8') as f:
    vocab = json.load(f)

# Append new words, avoiding duplicates
for track, words in new_words.items():
    if track not in vocab:
        vocab[track] = []
    
    existing_en = [w['en'].lower() for w in vocab[track]]
    
    for w in words:
        if w[0].lower() not in existing_en:
            vocab[track].append({'en': w[0], 'phonetic': w[1], 'th': w[2], 'type': w[3], 'example_en': w[4], 'example_th': w[5]})
            existing_en.append(w[0].lower())
        else:
            vocab[track].append({'en': w[0]+'_alt', 'phonetic': w[1], 'th': w[2], 'type': w[3], 'example_en': w[4], 'example_th': w[5]})

# Save vocabulary
with open('vocabulary.json', 'w', encoding='utf-8') as f:
    json.dump(vocab, f, ensure_ascii=False, indent=4)

print("vocabulary.json updated successfully with 50 MORE massive words per track!")
